"use client";

import { Calendar } from "@/components/calendar";
import { Panel } from "@/components/panel";
import { Timer } from "@/components/timer";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div className="grid grid-flow-col gap-4 [grid-template-columns:320px_208px]">
        <Calendar />

        <div className="w-52 grid grid-flow-row gap-4">
          <div className="font-['Open_Sans'] h-[70px] font-black text-[51px] text-center">
            20:54
          </div>

          <Timer />

          <Panel customStyle="grid items-center px-[16px] bg-gradient-to-r from-[#627594] to-[#a8b8d8] text-white h-[70px]">
            <div className="font-normal grid grid-flow-col justify-between items-center">
              <span className="text-[#ffffffb3] text-sm">連続：</span>
              <div>
                <span className="text-2xl">24</span>
                <span className="pl-1">日目</span>
              </div>
            </div>
          </Panel>
          <Panel customStyle="grid items-center px-[16px] bg-gradient-to-r from-[#627594] to-[#a8b8d8] text-white h-[70px]">
            <div className="font-normal grid grid-flow-col justify-between items-center">
              <span className="text-[#ffffffb3] text-sm">合計：</span>
              <div>
                <span className="text-2xl">56</span>
                <span className="pl-1">日</span>
              </div>
            </div>
          </Panel>
        </div>
      </div>
    </>
  );
}
